# pylint: disable=missing-module-docstring, missing-class-docstring, missing-function-docstring

from uuid import UUID
from datetime import datetime

class AlbumArtist:
    name: str
    id: UUID


class Chapter:
    start_position_ticks: int
    name: str
    image_path: str
    image_date_modified: datetime
    image_tag: str

class ExternalURL:
    name: str
    url: str

class ImageTags:
    additional_prop1: str
    additional_prop2: str
    additional_prop3: str

class MediaAttachment:
    codec: str
    codec_tag: str
    comment: str
    index: int
    file_name: str
    mime_type: str
    delivery_url: str

class MediaStream:
    codec: str
    codec_tag: str
    language: str
    color_range: str
    color_space: str
    color_transfer: str
    color_primaries: str
    dv_version_major: int
    dv_version_minor: int
    dv_profile: int
    dv_level: int
    rpu_present_flag: int
    el_present_flag: int
    bl_present_flag: int
    dv_bl_signal_compatibility_id: int
    comment: str
    time_base: str
    codec_time_base: str
    title: str
    video_range: str
    video_range_type: str
    video_do_vi_title: str
    localized_undefined: str
    localized_default: str
    localized_forced: str
    localized_external: str
    display_title: str
    nal_length_size: str
    is_interlaced: bool
    is_avc: bool
    channel_layout: str
    bit_rate: int
    bit_depth: int
    ref_frames: int
    packet_length: int
    channels: int
    sample_rate: int
    is_default: bool
    is_forced: bool
    height: int
    width: int
    average_frame_rate: int
    real_frame_rate: int
    profile: str
    type: str
    aspect_ratio: str
    index: int
    score: int
    is_external: bool
    delivery_method: str
    delivery_url: str
    is_external_url: bool
    is_text_subtitle_stream: bool
    supports_external_stream: bool
    path: str
    pixel_format: str
    level: int
    is_anamorphic: bool

class MediaSource:
    protocol: str
    id: str
    path: str
    encoder_path: str
    encoder_protocol: str
    type: str
    container: str
    size: int
    name: str
    is_remote: bool
    e_tag: str
    run_time_ticks: int
    read_at_native_framerate: bool
    ignore_dts: bool
    ignore_index: bool
    gen_pts_input: bool
    supports_transcoding: bool
    supports_direct_stream: bool
    supports_direct_play: bool
    is_infinite_stream: bool
    requires_opening: bool
    open_token: str
    requires_closing: bool
    live_stream_id: str
    buffer_ms: int
    requires_looping: bool
    supports_probing: bool
    video_type: str
    iso_type: str
    video3_d_format: str
    media_streams: list[MediaStream]
    media_attachments: list[MediaAttachment]
    formats: list[str]
    bitrate: int
    timestamp: str
    required_http_headers: ImageTags
    transcoding_url: str
    transcoding_sub_protocol: str
    transcoding_container: str
    analyze_duration_ms: int
    default_audio_stream_index: int
    default_subtitle_stream_index: int

class Person:
    name: str
    id: UUID
    role: str
    type: str
    primary_image_tag: str
    image_blur_hashes: dict[str, ImageTags]

class UserData:
    rating: int
    played_percentage: int
    unplayed_item_count: int
    playback_position_ticks: int
    play_count: int
    is_favorite: bool
    likes: bool
    last_played_date: datetime
    played: bool
    key: str
    item_id: str


class JellyfinLibraryItem:
    name: str
    original_title: str
    server_id: str
    id: UUID
    etag: str
    source_type: str
    playlist_item_id: str
    date_created: datetime
    date_last_media_added: datetime
    extra_type: str
    airs_before_season_number: int
    airs_after_season_number: int
    airs_before_episode_number: int
    can_delete: bool
    can_download: bool
    has_subtitles: bool
    preferred_metadata_language: str
    preferred_metadata_country_code: str
    supports_sync: bool
    container: str
    sort_name: str
    forced_sort_name: str
    video3_d_format: str
    premiere_date: datetime
    external_urls: list[ExternalURL]
    media_sources: list[MediaSource]
    critic_rating: int
    production_locations: list[str]
    path: str
    enable_media_source_display: bool
    official_rating: str
    custom_rating: str
    channel_id: UUID
    channel_name: str
    overview: str
    taglines: list[str]
    genres: list[str]
    community_rating: int
    cumulative_run_time_ticks: int
    run_time_ticks: int
    play_access: str
    aspect_ratio: str
    production_year: int
    is_place_holder: bool
    number: str
    channel_number: str
    index_number: int
    index_number_end: int
    parent_index_number: int
    remote_trailers: list[ExternalURL]
    provider_ids: ImageTags
    is_hd: bool
    is_folder: bool
    parent_id: UUID
    type: str
    people: list[Person]
    studios: list[AlbumArtist]
    genre_items: list[AlbumArtist]
    parent_logo_item_id: UUID
    parent_backdrop_item_id: UUID
    parent_backdrop_image_tags: list[str]
    local_trailer_count: int
    user_data: UserData
    recursive_item_count: int
    child_count: int
    series_name: str
    series_id: UUID
    season_id: UUID
    special_feature_count: int
    display_preferences_id: str
    status: str
    air_time: str
    air_days: list[str]
    tags: list[str]
    primary_image_aspect_ratio: int
    artists: list[str]
    artist_items: list[AlbumArtist]
    album: str
    collection_type: str
    display_order: str
    album_id: UUID
    album_primary_image_tag: str
    series_primary_image_tag: str
    album_artist: str
    album_artists: list[AlbumArtist]
    season_name: str
    media_streams: list[MediaStream]
    video_type: str
    part_count: int
    media_source_count: int
    image_tags: ImageTags
    backdrop_image_tags: list[str]
    screenshot_image_tags: list[str]
    parent_logo_image_tag: str
    parent_art_item_id: UUID
    parent_art_image_tag: str
    series_thumb_image_tag: str
    image_blur_hashes: dict[str, ImageTags]
    series_studio: str
    parent_thumb_item_id: UUID
    parent_thumb_image_tag: str
    parent_primary_image_item_id: str
    parent_primary_image_tag: str
    chapters: list[Chapter]
    location_type: str
    iso_type: str
    media_type: str
    end_date: datetime
    locked_fields: list[str]
    trailer_count: int
    movie_count: int
    series_count: int
    program_count: int
    episode_count: int
    song_count: int
    album_count: int
    artist_count: int
    music_video_count: int
    lock_data: bool
    width: int
    height: int
    camera_make: str
    camera_model: str
    software: str
    exposure_time: int
    focal_length: int
    image_orientation: str
    aperture: int
    shutter_speed: int
    latitude: int
    longitude: int
    altitude: int
    iso_speed_rating: int
    series_timer_id: str
    program_id: str
    channel_primary_image_tag: str
    start_date: datetime
    completion_percentage: int
    is_repeat: bool
    episode_title: str
    channel_type: str
    audio: str
    is_movie: bool
    is_sports: bool
    is_series: bool
    is_live: bool
    is_news: bool
    is_kids: bool
    is_premiere: bool
    timer_id: str
    current_program: str

class JellyfinLibrary:
    items: list[JellyfinLibraryItem]
    total_record_count: int
    start_index: int
