#!/bin/bash

regex_emojis=(
  "(?<=^feat(\(.*\))?(:)?)\s|✨"
  "(?<=^fix(\(.*\))?(:)?)\s|🐛"
  "(?<=^docs(\(.*\))?(:)?)\s|📚"
  "(?<=^style(\(.*\))?(:)?)\s|💎"
  "(?<=^refactor(\(.*\))?(:)?)\s|📦"
  "(?<=^perf(\(.*\))?(:)?)\s|🚀"
  "(?<=^test(\(.*\))?(:)?)\s|🚨"
  "(?<=^build(\(.*\))?(:)?)\s|👷"
  "(?<=^ci(\(.*\))?(:)?)\s|💚"
  "(?<=^chore(\(.*\))(:)?)\s|🔧"
  "(?<=^revert(\(.*\))(:)?)\s|⏪"
  "(?<=^release(\(.*\))(:)?)\s|🏹"
  "(?<=^dependabot(\(.*\))(:)?)\s|📦"
  "(?<=^first(\(.*\))(:)?)\s|🎉"
)

tests=(
  "feat test"
  "feat: test"
  "feat(test) test"
  "feat(test): test"
  "fix test"
  "fix: test"
  "fix(test) test"
  "fix(test): test"
  "docs test"
  "docs: test"
  "docs(test) test"
  "docs(test): test"
  "style test"
  "style: test"
  "style(test) test"
  "style(test): test"
  "refactor test"
  "refactor: test"
  "refactor(test) test"
  "refactor(test): test"
  "perf test"
  "perf: test"
  "perf(test) test"
  "perf(test): test"
  "test test"
  "test: test"
  "test(test) test"
  "test(test): test"
  "build test"
  "build: test"
  "build(test) test"
  "build(test): test"
  "ci test"
  "ci: test"
  "ci(test) test"
  "ci(test): test"
  "chore test"
  "chore: test"
  "chore(test) test"
  "chore(test): test"
  "revert test"
  "revert: test"
  "revert(test) test"
  "revert(test): test"
  "release test"
  "release: test"
  "release(test) test"
  "release(test): test"
  "dependabot test"
  "dependabot: test"
  "dependabot(test) test"
  "dependabot(test): test"
  "first test"
  "first: test"
  "first(test) test"
  "first(test): test"
)

for test in "${tests[@]}"; do
  for regex_emoji in "${regex_emojis[@]}"; do
    regex="${regex_emoji%%|*}"
    emoji="${regex_emoji##*|}"

    if [[ "$test" =~ $regex ]]; then
      test="${test/$regex/$emoji}"
      echo "$test"
    fi
  done
done