"""added multiple servers

Revision ID: 0271b864fd47
Revises: 56b33a2ca88e
Create Date: 2025-06-11 11:45:10.197908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0271b864fd47'
down_revision = '56b33a2ca88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'media_server' not in inspector.get_table_names():
        op.create_table('media_server',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('server_type', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('api_key', sa.String(), nullable=True),
        sa.Column('allow_downloads_plex', sa.Boolean(), nullable=False),
        sa.Column('allow_tv_plex', sa.Boolean(), nullable=False),
        sa.Column('verified', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_library_server_id_media_server', 'media_server', ['server_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_server_id_media_server', 'media_server', ['server_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_server_id_media_server', type_='foreignkey')
        batch_op.drop_column('server_id')

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_constraint('fk_library_server_id_media_server', type_='foreignkey')
        batch_op.drop_column('server_id')

    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'media_server' in inspector.get_table_names():
        op.drop_table('media_server')
    # ### end Alembic commands ###
