"""Add notes field to User model

Revision ID: 14a87d76dff1
Revises: d0a4dfc55dc4
Create Date: 2025-09-05 11:47:53.611095

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "14a87d76dff1"
down_revision = "d0a4dfc55dc4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("notes", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("notes")

    # ### end Alembic commands ###
