"""empty message

Revision ID: 124ededf80dc
Revises: 20250613_external_url
Create Date: 2025-06-17 18:59:31.983541

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "124ededf80dc"
down_revision = "20250613_external_url"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("identity", schema=None) as batch_op:
        batch_op.add_column(sa.Column("nickname", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("identity", schema=None) as batch_op:
        batch_op.drop_column("nickname")

    # ### end Alembic commands ###
