"""Added missing columns

Revision ID: 39514b0aaad9
Revises: 20250912_add_standardized_user_metadata_columns
Create Date: 2025-09-13 13:41:12.234668

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "39514b0aaad9"
down_revision = "20250912_add_standardized_user_metadata_columns"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_admin", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("is_admin")

    # ### end Alembic commands ###
