"""add notification events

Revision ID: 08a6c8fb44db
Revises: fd5a34530162
Create Date: 2025-10-04 13:05:16.517462

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "08a6c8fb44db"
down_revision = "fd5a34530162"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "notification_events",
                sa.String(),
                nullable=False,
                server_default="user_joined,update_available",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_column("notification_events")

    # ### end Alembic commands ###
