"""Added disabled attribute

Revision ID: fd5a34530162
Revises: 39514b0aaad9
Create Date: 2025-09-27 01:00:15.548258

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fd5a34530162"
down_revision = "39514b0aaad9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, add column as nullable first, then update values, then make NOT NULL
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_disabled", sa.Boolean(), nullable=True, default=False)
        )

    # Update all existing records to have is_disabled = False
    op.execute("UPDATE user SET is_disabled = 0 WHERE is_disabled IS NULL")

    # Now alter the column to be NOT NULL with proper default
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("is_disabled", nullable=False, server_default="0")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("is_disabled")

    # ### end Alembic commands ###
