"""Make emails nullable

Revision ID: 23bf17eccf13
Revises: 20250612_add_identity_table
Create Date: 2025-06-11 21:09:27.144846

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision = '23bf17eccf13'
down_revision = '20250612_add_identity_table'
branch_labels = None
depends_on = None


def upgrade():
    # Set a default value for NULL created_at before making it NOT NULL
    op.execute(
        f"UPDATE identity SET created_at = '{datetime.now(timezone.utc).isoformat()}' WHERE created_at IS NULL"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
