"""Added Library Table

Revision ID: 490af4233e95
Revises: 9e13976c0cfa
Create Date: 2025-05-23 22:07:01.374607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490af4233e95'
down_revision = '9e13976c0cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('invite_library',
    sa.Column('invite_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['invitation.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.PrimaryKeyConstraint('invite_id', 'library_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_library')
    op.drop_table('library')
    # ### end Alembic commands ###
