"""added live tv

Revision ID: 56b33a2ca88e
Revises: 490af4233e95
Create Date: 2025-06-03 12:49:43.589942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b33a2ca88e'
down_revision = '490af4233e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plex_allow_channels', sa.Boolean(), nullable=True))
        batch_op.alter_column('plex_allow_sync',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('plex_home',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.alter_column('plex_home',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('plex_allow_sync',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('plex_allow_channels')

    # ### end Alembic commands ###
