"""Add ApiKey model for database-stored API keys

Revision ID: 644b740dca24
Revises: 0597748a6fef
Create Date: 2025-07-28 12:06:36.446910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644b740dca24'
down_revision = '0597748a6fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    # SQLite doesn't handle dropping unnamed foreign key constraints well with batch operations
    # Instead, we'll recreate the table with the proper CASCADE constraints
    op.drop_table('invitation_server')
    op.create_table('invitation_server',
        sa.Column('invite_id', sa.Integer(), nullable=False),
        sa.Column('server_id', sa.Integer(), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['invite_id'], ['invitation.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['server_id'], ['media_server.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('invite_id', 'server_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse the recreation by dropping and recreating without CASCADE
    op.drop_table('invitation_server')
    op.create_table('invitation_server',
        sa.Column('invite_id', sa.Integer(), nullable=False),
        sa.Column('server_id', sa.Integer(), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['invite_id'], ['invitation.id']),
        sa.ForeignKeyConstraint(['server_id'], ['media_server.id']),
        sa.PrimaryKeyConstraint('invite_id', 'server_id')
    )

    op.drop_table('api_key')
    # ### end Alembic commands ###
