"""add_password_reset_token_table

Revision ID: a052ac2ce6a9
Revises: 8ef04799f27f
Create Date: 2025-11-20 21:32:39.100413

whats new?
1. Adds a new table `password_reset_token` to store tokens for user password resets.
2. The table includes fields for token code, associated user, creation and expiration timestamps, and usage status.

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a052ac2ce6a9"
down_revision = "8ef04799f27f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("password_reset_token")
    # ### end Alembic commands ###
