"""removed password plainstring

Revision ID: e6006b5e374e
Revises: 91865b5a23d2
Create Date: 2025-07-08 18:24:57.211580

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e6006b5e374e"
down_revision = "91865b5a23d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("password")

    with op.batch_alter_table("wizard_bundle_step", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_bundle_pos", ["bundle_id", "position"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wizard_bundle_step", schema=None) as batch_op:
        batch_op.drop_constraint("uq_bundle_pos", type_="unique")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password", sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
