"""Add Telegram notification fields

Revision ID: e6155a91eb50
Revises: eecad7c18ac3
Create Date: 2026-01-23 21:24:46.280461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6155a91eb50'
down_revision = 'eecad7c18ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_bot_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('telegram_chat_id')
        batch_op.drop_column('telegram_bot_token')
    # ### end Alembic commands ###
