# Generated by https://quicktype.io


class JellyfinUserPolicy:
    type: str
    title: str
    status: int
    detail: str
    instance: str
    additional_prop1: str
    additional_prop2: str
    additional_prop3: str

    def __init__(self, type: str, title: str, status: int, detail: str, instance: str, additional_prop1: str, additional_prop2: str, additional_prop3: str) -> None:
        self.type = type
        self.title = title
        self.status = status
        self.detail = detail
        self.instance = instance
        self.additional_prop1 = additional_prop1
        self.additional_prop2 = additional_prop2
        self.additional_prop3 = additional_prop3
