#!/usr/bin/env sh

[ -n "$CI" ] && exit 0

. "$(dirname -- "$0")/_/husky.sh"

npx --no-install commitlint --edit "$1"

filepath="$1"
tmp_file=$(mktemp /tmp/emoji-commitzen.XXXX)

replacements=(
    's/^feat/✨ feat/'
    's/^fix/🐝 fix/'
    's/^doc/📚 doc/'
    's/^style/🎨 style/'
    's/^refactor/🔨 refactor/'
    's/^perf/🚀 perf/'
    's/^chore/🔧 chore/'
    's/^lint/💄 lint/'
    's/^test/🚨 test/'
    's/^first/🐣 first/'
)

sed_command=$(printf "%s;" "${replacements[@]}")
cat $filepath | sed "$sed_command" > $tmp_file
mv $tmp_file $filepath
