name: Compile Translations

on:
    push:
        branches:
            - translations
    workflow_dispatch: {}

permissions:
    packages: write

jobs:
    compile:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            # Checkout the repo and the translations branch
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: translations

            # Install dependencies node and npm
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y nodejs npm gettext

            # Install dependencies for frontend
            - name: Install dependencies for frontend
              run: |
                  npm install vue3-gettext

            # Compile translations
            - name: Compile translations
              run: |
                  cd apps/wizarr-frontend/
                  npx vue-gettext-compile

            # Commit and push changes
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: 'Compile translations'
                  file_pattern: '**/translations.json'
                  branch: translations
